portable run-it scripts

diff --git a/deploy/bin/run-job b/deploy/bin/run-job
--- a/deploy/bin/run-job
+++ b/deploy/bin/run-job
@@ -1,26 +1,22 @@
 #!/usr/bin/env bash
 set -eou pipefail
 
-dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-src_dir="${dir}/../../src"
+dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../" && pwd )" && cd "$dir"
+app="$(basename $(pwd))"
+src_dir="${dir}/src"
 _job="$1"
 set +u; _date="$2"; set -u
 cmd=''
 
 prereqs(){
   if [[ $(whoami) == 'root' ]]; then
-    case $(uname -a) in
-      *arm* )
-        set +e; eval "${dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; ;; # set +e when apk not available
+    case "$(uname -m)" in
+      arm* )
+        deploy_dir='/usr/local/deploy/bin'
+        set +e; eval "${deploy_dir}/apk-arm"; update-ca-certificates; apk fix || echo 'Unable to reach apk...'; set -e; # set +e when apk not available
+        mv /app.jar "${tmp_dir}/${app}.jar" ;;
     esac
-
-    case $(cat /etc/os-release | grep -i '^name=' | sed 's/NAME=//' | sed 's/^"\(.*\)"$/\1/') in
-      'Alpine Linux' )
-        update-ca-certificates; apk fix || echo 'Unable to reach apk...' ;; # Any quirks with Alpine can go here
-      'Debian GNU/Linux' )
-        echo '' ;; # Any quirks with Debian can go here
-    esac
-  fi
+fi
 }
 
 case "$_job" in
